baseurl = "https://acod.io/"
languageCode = "en-us"
theme = "terminal"
pagination.pagerSize = 5

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 7
  fullWidthTheme = false
  centerTheme = false
  favicon = "favicon.svg"

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "ArtIntoScience"
  site = "ArtIntoScience"

[languages]
  [languages.en]
    title = "ACoD"
    subtitle = "A Conference on Defense"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "ACoD"
      logoHomeLink = "/"

    [languages.en.menu]
        [[languages.en.menu.main]]
        identifier = "tickets"
        name = "Tickets"
        url = "https://www.zeffy.com/en-US/ticketing/e6b8943c-d7e1-417d-8335-b3f44d6b1f8a"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "cfp"
        name = "CFP"
        url = "/cfp"
      [[languages.en.menu.main]]
        identifier = "coc"
        name = "Code of Conduct"
        url = "/coc"
      [[languages.en.menu.main]]
        identifier = "schedule"
        name = "Schedule and Venue"
        url = "/Schedule"
      [[languages.en.menu.main]]
        identifier = "sponsors"
        name = "Sponsors"
        url = "/sponsors"
