baseurl = "https://artintoscience.com/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "blue"
  showMenuItems = 6
  fullWidthTheme = false
  centerTheme = false
  favicon = "favicon.svg"

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "ArtIntoScience"
  site = "ArtIntoScience"

[languages]
  [languages.en]
    title = "Art into Science"
    subtitle = "Art into Science - A Conference on Defense"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "ACoD"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
    [[languages.en.menu.main]]
        identifier = "speakers"
        name = "Speakers"
        url = "/speakers"
      [[languages.en.menu.main]]
        identifier = "cfp"
        name = "Call for Speakers"
        url = "/cfp"
      [[languages.en.menu.main]]
        identifier = "coc"
        name = "Code of Conduct"
        url = "/coc"
      [[languages.en.menu.main]]
        identifier = "schedule"
        name = "Schedule and Venue"
        url = "/Schedule"
      [[languages.en.menu.main]]
        identifier = "sponsors"
        name = "Sponsors"
        url = "/sponsors"
