baseurl = "https://artintoscience.github.io/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "Terminal"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Terminal"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "cfp"
        name = "Call for Speakers"
        url = "/cfp"
      [[languages.en.menu.main]]
        identifier = "coc"
        name = "Code of Conduct"
        url = "/coc"
      [[languages.en.menu.main]]
        identifier = "schedule"
        name = "Schedule and Venue"
        url = "/Schedule"
